language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.0
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - QEMU_AUDIO_DRV=none 

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    # TODO: why is this here explicitly in addition to $ANDROID_TARGET below
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    # The SDK version used to compile your project
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  # Accept sdk licenses
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

before_script:
  # Get gradle
  - chmod +x gradlew
  
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
  # The app will now automatically be installed and tested via
  # the command `gradle connectedCheck`
